# Generated by Django 5.2.1 on 2025-05-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_storemembers_storemember"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cost",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
