# Generated by Django 5.2 on 2025-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_status_remove_order_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='thumbnail',
            field=models.ImageField(blank=True, default='store/immages/default.svg', upload_to='store/images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='store/images/default.svg', upload_to='store/images/products/'),
        ),
    ]
