# Generated by Django 5.2 on 2025-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_thumbnail_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/default.svg', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/default.svg', upload_to='images/thumbnails/'),
        ),
    ]
