# Generated by Django 5.2 on 2025-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_libraryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/default.svg', upload_to='images/store/products/'),
        ),
    ]
