from django.db import models

class User (models.Model):
    user_name = models.CharField(max_length=300)
    user_password = models.CharField(max_length=32)
    date_of_birth = models.DateField("Date of Birth")
    user_wallet = models.FloatField(default=0)
    # UserID is autogenerated by Django
    def __str__(self):
        return self.username
        

class Store (models.Model):
    store_name = models.CharField(max_length=32)
    store_desc = models.CharField(max_length=2000)
    store_thumbnail = models.URLField(max_length=200, blank=True,default="")
    # StoreID is autogenerated by Django
    def __str__(self):
        return self.storeName

    
class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null= True)
    product_name = models.CharField(max_length=32)
    product_description = models.CharField(max_length=2000)
    product_price = models.FloatField(default=0)
    store_thumbnail = models.URLField(max_length=200)
    # ProductId is autogenerated by Django
    def __str__(self):
        return self.productName
    
    
class WishlistItem (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null= True)
    product = models.ForeignKey(Product,on_delete=models.DO_NOTHING, null= True)
    # WishlistItemID is autogenerated by Django
    def __str__(self):
        return self.user + self.product
    
    def __init__(self, user : User, product : Product):
        self.user = user
        self.product = product
        
        
        
    

    
