from django.db import models

class User (models.Model):
    username = models.CharField(max_length=300)
    password = models.CharField(max_length=32)
    dateOfBirth = models.DateField("Date of Birth")
    wallet = models.FloatField(default=0)
    # UserID is autogenerated by Django
    def __str__(self):
        return self.username
        

class Store (models.Model):
    storeName = models.CharField(max_length=32)
    storeDesc = models.CharField(max_length=2000)
    storeThumbnail = models.URLField(max_length=200)
    # StoreID is autogenerated by Django
    def __str__(self):
        return self.storeName

    
class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    productName = models.CharField(max_length=32)
    productDescription = models.CharField(max_length=2000)
    productPrice = models.FloatField(default=0)
    storeThumbnail = models.URLField(max_length=200)
    # ProductId is autogenerated by Django
    def __str__(self):
        return self.productName
    
    
class WishlistItem (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.DO_NOTHING)
    # WishlistItemID is autogenerated by Django
    def __str__(self):
        return self.user + self.product
    
    def __init__(self, user : User, product : Product):
        self.user = user
        self.product = product
        
        
        
    

    
