# Generated by Django 5.1.7 on 2025-03-13 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=32)),
                ("store_desc", models.CharField(max_length=2000)),
                ("store_thumbnail", models.URLField(blank=True, default="")),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="productDescription",
            new_name="product_description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="productName",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="productPrice",
            new_name="product_price",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="dateOfBirth",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="user_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="user_password",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="wallet",
            new_name="user_wallet",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="userId",
        ),
        migrations.AddField(
            model_name="product",
            name="store_thumbnail",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="home.product",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.user"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.store"
            ),
        ),
    ]
