# Generated by Django 5.1.7 on 2025-03-13 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_category_itemcategory_usertransaction_userpayment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertransaction",
            name="product",
        ),
        migrations.AddField(
            model_name="usertransaction",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.user"
            ),
        ),
    ]
