# Generated by Django 5.2 on 2025-05-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_usertransaction_product_usertransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.URLField(null=True),
        ),
    ]
